### PR TITLE
Added basic solidity test for YourContract

### LINKED ISSUE #25: Add basic solidity test for YourContract

### PR DESCRIPTION
**Pull request by paschal533**
## Description

Added basic solidity hardhat test for YourContract

## Additional Information

- [x] I have read the [contributing docs](/fil-frame/fil-frame-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/fil-frame/fil-frame-2/pulls)

## Related Issues
- fixed #25

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by paschal533** [comment]
Should I go ahead and delect "fil-frame\packages\hardhat\test\Lock.ts" file @xBalbinus and @lordshashank ?

**Comment by lordshashank** [comment]
Hey @paschal533 again there are like 139 files changed, ig you are running whole workspace linting or something which is leading to this, we are changing the contracts by shifting them to deal client contracts, it would be better to add tests after that, maybe just wait a few days for this issue :)

**Comment by paschal533** [comment]
> Hey @paschal533 again there are like 139 files changed, ig you are running whole workspace linting or something which is leading to this, we are changing the contracts by shifting them to deal client contracts, it would be better to add tests after that, maybe just wait a few days for this issue :)

My bad.... I used "git add -A" instead of "git add ." .  Alright then, I will wait for a few days to write the test.

**Comment by paschal533** [comment]
> Hey @paschal533 again there are like 139 files changed, ig you are running whole workspace linting or something which is leading to this, we are changing the contracts by shifting them to deal client contracts, it would be better to add tests after that, maybe just wait a few days for this issue :)

I fixed the issue... thanks @lordshashank

**Pull request closed without merging**
