### PR TITLE
Feat: Add deterministic deployment for same addresses

### LINKED ISSUE #32: Integrate deterministic deployment to allow users to deploy at same addresses across chains

### PR DESCRIPTION
**Pull request by MattWong-ca**
## Description

- Add deterministic deployment so users can deploy a contract to the same addresses across different EVM chains.
- This doc was [referenced](https://www.quicknode.com/guides/ethereum-development/smart-contracts/how-to-use-create2-to-predetermine-contract-addresses)
## Additional Information

- [x] I have read the [contributing docs](/fil-frame/fil-frame-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/fil-frame/fil-frame-2/pulls)

## Related Issues

Closes #32 

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by lordshashank** [comment]
Hey @MattWong-ca , great work. Could you please remove the `yourContract` and implement this for the current `DealClient` and `DealInfo` contract.

**Comment by xBalbinus** [comment]
No need; feel free to merge this to a different branch. I think this belongs on the axelar-specific integration branch @lordshashank

**Comment by lordshashank** [comment]
Ah yeah ohk, @MattWong-ca please redirect the pr to different branch not the main one.

**Comment by MattWong-ca** [comment]
> Ah yeah ohk, @MattWong-ca please redirect the pr to different branch not the main one.

Just did! I created `axelar-integration` branch from `filfoxVerification` branch (since that seems to be last PR before deal client contracts were merged), and set this PR to be merged into it instead.

**Review by xBalbinus — APPROVED** [review]

**Pull request merged**
